name: test_app_najafi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_riverpod:
  dio:
  get_it:
  flutter_hooks:
  hooks_riverpod:
  logger:
  retrofit:
  json_annotation:
  go_router:
  flutter_localizations:
    sdk: flutter
  intl: any
  dartz:
  riverpod_annotation:
  curl_logger_dio_interceptor:
  very_good_analysis:
  flutter_secure_storage:
  flutter_form_builder:
  form_builder_validators:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
#  retrofit_generator:
  build_runner:
  json_serializable:
  riverpod_generator:

flutter:
  uses-material-design: true
  generate: true
